export const ADD_ARTICLE_REQUESTED = "ADD_ARTICLE_REQUESTED"
export const ADD_ARTICLE_RECIEVED_OK = "ADD_ARTICLE_RECIEVED"
export const REMOVE_ARTICLE_REQUESTED = "REMOVE_ARTICLE_REQUESTED"
export const REMOVE_ARTICLE_RECIEVED_OK = "REMOVE_ARTICLE_RECIEVED"
